# Generated by Django 4.1.4 on 2022-12-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
