# Generated by Django 4.1.4 on 2022-12-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_block_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='hierarchy',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
